[tool.poetry]
name = "sample-openai"
version = "0.1.0"
description = ""
authors = ["tatsuki1107 <tatsuki11070522@icloud.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
openai = "^0.27.2"
jupyterlab = "3.2.1"
pandas = "1.2.0"
matplotlib = "^3.4.1"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
